import type { Stage } from './types'

// Stage 1: Baseline
export const stage1: Stage = {
  id: 'stage-1',
  title: 'Baseline',
  subtitle: 'Single Server — Healthy Metrics',
  insight: 'Server at 15% CPU — comfortable headroom.',
  displayTitle: 'Baseline Architecture',
  description: 'Single server handling all traffic. Healthy metrics at low load.',
  components: ['Client', 'Server', 'Database'],
  infoCard: {
    technicalTerm: 'Monolithic Single-Server',
    whenHappens: 'Early in development. Low, predictable traffic on a single server.',
    whatCondition: '100 RPS at 15% CPU. One process handles web, logic, and DB with room to spare.',
    howToResolve: 'Healthy baseline. Problems emerge as traffic grows — subsequent stages show what breaks first.',
  },
  nodes: [
    { id: 'client', label: 'Client', type: 'client', x: 150, y: 200 },
    { id: 'server', label: 'Server', type: 'server', x: 450, y: 200 },
    { id: 'database', label: 'Database', type: 'database', x: 750, y: 200 },
  ],
  edges: [
    { id: 'client-server', from: 'client', to: 'server' },
    { id: 'server-db', from: 'server', to: 'database' },
  ],
  viewBox: '0 0 900 400',
}

// Stage 2: Stateful Auth with Fix
export const stage2: Stage = {
  id: 'stage-2',
  title: 'Stateful Auth',
  subtitle: 'In-Memory Auth — CPU Spikes at 5K RPS',
  insight: 'Server checks auth in-memory. CPU jumps to 75%.',
  displayTitle: 'Stateful Authentication Problem',
  description: 'Server stores session data in memory. Auth check runs in-process per request, causing CPU overhead.',
  components: ['Client', 'Server', 'Database'],
  infoCard: {
    technicalTerm: 'Stateful Server',
    whenHappens: 'User auth lives in server memory. Works on one server; breaks under horizontal scaling.',
    whatCondition: '5K RPS adds 30% CPU overhead from in-memory session lookups. Cannot scale out without sticky routing.',
    howToResolve: 'Move sessions to Redis. Server becomes stateless — any replica handles any request.',
  },
  fixModes: [
    {
      nodes: [
        { id: 'client', label: 'Client', type: 'client', x: 120, y: 220 },
        { id: 'server', label: 'Server', type: 'server', x: 420, y: 220 },
        { id: 'session-store', label: 'Session Store', type: 'session-store', x: 420, y: 360 },
        { id: 'database', label: 'Database', type: 'database', x: 820, y: 220 },
      ],
      edges: [
        { id: 'client-server', from: 'client', to: 'server' },
        { id: 'server-store', from: 'server', to: 'session-store' },
        { id: 'server-db', from: 'server', to: 'database' },
      ],
      viewBox: '0 0 1000 440',
      engineId: 'stage-3',
      enterLabel: 'Apply Fix: Go Stateless',
      description: 'Sessions offloaded to Redis. Server CPU drops to 45%. No sticky sessions needed.',
    },
  ],
  nodes: [
    { id: 'client', label: 'Client', type: 'client', x: 150, y: 200 },
    { id: 'server', label: 'Server', type: 'server', x: 450, y: 200 },
    { id: 'database', label: 'Database', type: 'database', x: 750, y: 200 },
  ],
  edges: [
    { id: 'client-server', from: 'client', to: 'server' },
    { id: 'server-db', from: 'server', to: 'database' },
  ],
  viewBox: '0 0 900 400',
}

// Stage 3: API Gateway & Rate Limiting
export const stage3: Stage = {
  id: 'stage-api-gw',
  title: 'API Gateway',
  subtitle: 'Validate & Rate-Limit Incoming Requests',
  insight: 'Stateless server healthy but unfiltered traffic causes CPU spike. Gateway filters bad requests.',
  displayTitle: 'API Gateway & Rate Limiting',
  description: 'Server is stateless but all raw traffic hits it. Add API Gateway to filter, validate, and rate-limit.',
  components: ['Client', 'Server', 'API Gateway', 'Session Store', 'Database'],
  infoCard: {
    technicalTerm: 'API Gateway & Rate Limiting',
    whenHappens: 'Stateless servers are ready, but unfiltered traffic hits them directly.',
    whatCondition: '13K RPS hits server without filtering. Bots + malformed requests spike CPU to 95% with 20%+ error rate.',
    howToResolve: 'Add API Gateway as single entry point — validates, rate-limits, and rejects bad traffic at the edge.',
  },
  fixModes: [
    {
      nodes: [
        { id: 'client', label: 'Client', type: 'client', x: 100, y: 220 },
        { id: 'api-gateway', label: 'API Gateway', type: 'api-gateway', x: 300, y: 220 },
        { id: 'server', label: 'Server', type: 'server', x: 560, y: 220 },
        { id: 'session-store', label: 'Session Store', type: 'session-store', x: 560, y: 360 },
        { id: 'database', label: 'Database', type: 'database', x: 920, y: 220 },
      ],
      edges: [
        { id: 'client-gw', from: 'client', to: 'api-gateway' },
        { id: 'gw-server', from: 'api-gateway', to: 'server' },
        { id: 'server-store', from: 'server', to: 'session-store' },
        { id: 'server-db', from: 'server', to: 'database' },
      ],
      viewBox: '0 0 1100 440',
      engineId: 'stage-agw-fix',
      enterLabel: 'Add API Gateway',
      description: 'API Gateway filters bad traffic. 20% rejected, server CPU drops to 38%.',
      whatCondition: '12K attempted RPS. Gateway rejects 20% (bots, malformed). 9.6K clean requests reach server at 38% CPU.',
      howToResolve: 'Gateway acts as traffic filter. Servers handle only validated, rate-limited requests.',
    },
  ],
  nodes: [
    { id: 'client', label: 'Client', type: 'client', x: 120, y: 220 },
    { id: 'server', label: 'Server', type: 'server', x: 420, y: 220 },
    { id: 'session-store', label: 'Session Store', type: 'session-store', x: 420, y: 360 },
    { id: 'database', label: 'Database', type: 'database', x: 820, y: 220 },
  ],
  edges: [
    { id: 'client-server', from: 'client', to: 'server' },
    { id: 'server-store', from: 'server', to: 'session-store' },
    { id: 'server-db', from: 'server', to: 'database' },
  ],
  viewBox: '0 0 1000 440',
}

// Stage 4: Load Balancer & Health Checks
export const stage4: Stage = {
  id: 'stage-loadbalancer',
  title: 'Load Balancer',
  subtitle: 'Distribute Load & Detect Failures',
  insight: 'API Gateway with single server can\'t handle 10K RPS. Need horizontal scaling.',
  displayTitle: 'Horizontal Scaling & Load Balancing',
  description: 'Single server can\'t scale further. Add more servers, then add load balancer to distribute evenly.',
  components: ['Client', 'API Gateway', 'Load Balancer', 'Server ×3', 'Session Store', 'Database'],
  infoCard: {
    technicalTerm: 'Horizontal Scaling & Load Balancing',
    whenHappens: 'Traffic exceeds single server capacity. Vertical scaling hits limits.',
    whatCondition: '10K RPS overwhelms single server at 95% CPU. One server dying takes down all traffic.',
    howToResolve: 'Add servers horizontally. Load balancer distributes evenly and health-checks routing around failures.',
  },
  fixModes: [
    {
      nodes: [
        { id: 'client', label: 'Client', type: 'client', x: 80, y: 220 },
        { id: 'api-gateway', label: 'API Gateway', type: 'api-gateway', x: 280, y: 220 },
        { id: 'server-1', label: 'Server 1', type: 'server', x: 500, y: 110 },
        { id: 'server-2', label: 'Server 2', type: 'server', x: 500, y: 220 },
        { id: 'server-3', label: 'Server 3', type: 'server', x: 500, y: 330 },
        { id: 'session-store', label: 'Session Store', type: 'session-store', x: 750, y: 380 },
        { id: 'database', label: 'Database', type: 'database', x: 950, y: 220 },
      ],
      edges: [
        { id: 'client-gw', from: 'client', to: 'api-gateway' },
        { id: 'gw-s1', from: 'api-gateway', to: 'server-1' },
        { id: 'gw-s2', from: 'api-gateway', to: 'server-2' },
        { id: 'gw-s3', from: 'api-gateway', to: 'server-3' },
        { id: 's1-store', from: 'server-1', to: 'session-store' },
        { id: 's2-store', from: 'server-2', to: 'session-store' },
        { id: 's3-store', from: 'server-3', to: 'session-store' },
        { id: 's1-db', from: 'server-1', to: 'database' },
        { id: 's2-db', from: 'server-2', to: 'database' },
        { id: 's3-db', from: 'server-3', to: 'database' },
      ],
      viewBox: '0 0 1150 460',
      engineId: 'stage-lb-hotspot',
      enterLabel: 'Add More Servers',
      description: '3 servers added but no LB. Gateway routes unevenly. Server-1 hotspot at 72% CPU.',
      whatCondition: '9K RPS, 3 servers, but 70% routes to server-1. Servers 2 and 3 idle at 15%.',
      howToResolve: 'Add Load Balancer to distribute evenly and route around failed servers.',
    },
    {
      nodes: [
        { id: 'client', label: 'Client', type: 'client', x: 80, y: 220 },
        { id: 'api-gateway', label: 'API Gateway', type: 'api-gateway', x: 280, y: 220 },
        { id: 'load-balancer', label: 'Load Balancer', type: 'load-balancer', x: 460, y: 220 },
        { id: 'server-1', label: 'Server 1', type: 'server', x: 650, y: 110 },
        { id: 'server-2', label: 'Server 2', type: 'server', x: 650, y: 220 },
        { id: 'server-3', label: 'Server 3', type: 'server', x: 650, y: 330 },
        { id: 'session-store', label: 'Session Store', type: 'session-store', x: 850, y: 380 },
        { id: 'database', label: 'Database', type: 'database', x: 1050, y: 220 },
      ],
      edges: [
        { id: 'client-gw', from: 'client', to: 'api-gateway' },
        { id: 'gw-lb', from: 'api-gateway', to: 'load-balancer' },
        { id: 'lb-s1', from: 'load-balancer', to: 'server-1' },
        { id: 'lb-s2', from: 'load-balancer', to: 'server-2' },
        { id: 'lb-s3', from: 'load-balancer', to: 'server-3' },
        { id: 's1-store', from: 'server-1', to: 'session-store' },
        { id: 's2-store', from: 'server-2', to: 'session-store' },
        { id: 's3-store', from: 'server-3', to: 'session-store' },
        { id: 's1-db', from: 'server-1', to: 'database' },
        { id: 's2-db', from: 'server-2', to: 'database' },
        { id: 's3-db', from: 'server-3', to: 'database' },
      ],
      viewBox: '0 0 1250 460',
      engineId: 'stage-lb-balanced',
      enterLabel: 'Add Load Balancer',
      description: 'LB distributes evenly. Health checks detect failures. Each server 30% CPU.',
      whatCondition: '9K RPS via LB: 3K per server, 30% CPU each. Dead servers auto-removed by health checks.',
      howToResolve: 'LB + API Gateway = solid multi-tier foundation with fault tolerance.',
    },
  ],
  nodes: [
    { id: 'client', label: 'Client', type: 'client', x: 100, y: 220 },
    { id: 'api-gateway', label: 'API Gateway', type: 'api-gateway', x: 300, y: 220 },
    { id: 'server', label: 'Server', type: 'server', x: 560, y: 220 },
    { id: 'session-store', label: 'Session Store', type: 'session-store', x: 560, y: 360 },
    { id: 'database', label: 'Database', type: 'database', x: 920, y: 220 },
  ],
  edges: [
    { id: 'client-gw', from: 'client', to: 'api-gateway' },
    { id: 'gw-server', from: 'api-gateway', to: 'server' },
    { id: 'server-store', from: 'server', to: 'session-store' },
    { id: 'server-db', from: 'server', to: 'database' },
  ],
  viewBox: '0 0 1100 440',
}

// Shared cache node positions (used by stage5 fix1, stage6)
const cacheNodes = [
  { id: 'client', label: 'Client', type: 'client' as const, x: 60, y: 220 },
  { id: 'api-gateway', label: 'API Gateway', type: 'api-gateway' as const, x: 180, y: 220 },
  { id: 'load-balancer', label: 'Load Balancer', type: 'load-balancer' as const, x: 310, y: 220 },
  { id: 'server-1', label: 'Server 1', type: 'server' as const, x: 440, y: 110 },
  { id: 'server-2', label: 'Server 2', type: 'server' as const, x: 440, y: 220 },
  { id: 'server-3', label: 'Server 3', type: 'server' as const, x: 440, y: 330 },
  { id: 'session-store', label: 'Session Store', type: 'session-store' as const, x: 560, y: 400 },
  { id: 'cache-1', label: 'Cache 1', type: 'cache' as const, x: 620, y: 110 },
  { id: 'cache-2', label: 'Cache 2', type: 'cache' as const, x: 620, y: 220 },
  { id: 'cache-3', label: 'Cache 3', type: 'cache' as const, x: 620, y: 330 },
  { id: 'database', label: 'Database', type: 'database' as const, x: 800, y: 220 },
]

// Redis cluster nodes (used by stage5 fix3)
const cacheClusterNodes = [
  { id: 'client', label: 'Client', type: 'client' as const, x: 60, y: 220 },
  { id: 'api-gateway', label: 'API Gateway', type: 'api-gateway' as const, x: 180, y: 220 },
  { id: 'load-balancer', label: 'Load Balancer', type: 'load-balancer' as const, x: 310, y: 220 },
  { id: 'server-1', label: 'Server 1', type: 'server' as const, x: 440, y: 110 },
  { id: 'server-2', label: 'Server 2', type: 'server' as const, x: 440, y: 220 },
  { id: 'server-3', label: 'Server 3', type: 'server' as const, x: 440, y: 330 },
  { id: 'session-store', label: 'Session Store', type: 'session-store' as const, x: 560, y: 400 },
  { id: 'cache-1', label: 'Node 1', type: 'cache-cluster' as const, x: 620, y: 110 },
  { id: 'cache-2', label: 'Node 2', type: 'cache-cluster' as const, x: 620, y: 220 },
  { id: 'cache-3', label: 'Node 3', type: 'cache-cluster' as const, x: 620, y: 330 },
  { id: 'database', label: 'Database', type: 'database' as const, x: 800, y: 220 },
]

const cacheEdges = [
  { id: 'client-gw', from: 'client', to: 'api-gateway' },
  { id: 'gw-lb', from: 'api-gateway', to: 'load-balancer' },
  { id: 'lb-s1', from: 'load-balancer', to: 'server-1' },
  { id: 'lb-s2', from: 'load-balancer', to: 'server-2' },
  { id: 'lb-s3', from: 'load-balancer', to: 'server-3' },
  { id: 's2-store', from: 'server-2', to: 'session-store' },
  // Direct one-to-one server → cache (no cross-connections)
  { id: 's1-cache1', from: 'server-1', to: 'cache-1' },
  { id: 's2-cache2', from: 'server-2', to: 'cache-2' },
  { id: 's3-cache3', from: 'server-3', to: 'cache-3' },
  // Cache → DB misses
  { id: 'cache1-db', from: 'cache-1', to: 'database' },
  { id: 'cache2-db', from: 'cache-2', to: 'database' },
  { id: 'cache3-db', from: 'cache-3', to: 'database' },
]

const cacheViewBox = '0 0 1200 470'
const replicaViewBox = '0 0 950 470'

// DB replication nodes (used by stage6 fix)
const dbReplicationNodes = [
  { id: 'client', label: 'Client', type: 'client' as const, x: 60, y: 220 },
  { id: 'api-gateway', label: 'API Gateway', type: 'api-gateway' as const, x: 180, y: 220 },
  { id: 'load-balancer', label: 'Load Balancer', type: 'load-balancer' as const, x: 310, y: 220 },
  { id: 'server-1', label: 'Server 1', type: 'server' as const, x: 440, y: 110 },
  { id: 'server-2', label: 'Server 2', type: 'server' as const, x: 440, y: 220 },
  { id: 'server-3', label: 'Server 3', type: 'server' as const, x: 440, y: 330 },
  { id: 'session-store', label: 'Session Store', type: 'session-store' as const, x: 560, y: 400 },
  { id: 'cache-1', label: 'Node 1', type: 'cache-cluster' as const, x: 620, y: 110 },
  { id: 'cache-2', label: 'Node 2', type: 'cache-cluster' as const, x: 620, y: 220 },
  { id: 'cache-3', label: 'Node 3', type: 'cache-cluster' as const, x: 620, y: 330 },
  { id: 'db-primary', label: 'DB Primary', type: 'database' as const, x: 820, y: 150 },
  { id: 'db-replica-1', label: 'Replica 1', type: 'db-replica' as const, x: 820, y: 290 },
  { id: 'db-replica-2', label: 'Replica 2', type: 'db-replica' as const, x: 820, y: 400 },
]

// DB replication edges (used by stage6 fix)
const dbReplicationEdges = [
  { id: 'client-gw', from: 'client', to: 'api-gateway' },
  { id: 'gw-lb', from: 'api-gateway', to: 'load-balancer' },
  { id: 'lb-s1', from: 'load-balancer', to: 'server-1' },
  { id: 'lb-s2', from: 'load-balancer', to: 'server-2' },
  { id: 'lb-s3', from: 'load-balancer', to: 'server-3' },
  { id: 's2-store', from: 'server-2', to: 'session-store' },
  // Direct one-to-one server → cache cluster (no cross-connections)
  { id: 's1-cache1', from: 'server-1', to: 'cache-1' },
  { id: 's2-cache2', from: 'server-2', to: 'cache-2' },
  { id: 's3-cache3', from: 'server-3', to: 'cache-3' },
  // Cache → DB/replicas (one cache per replica for clarity)
  { id: 'cache1-dbp', from: 'cache-1', to: 'db-primary' },
  { id: 'cache2-r1', from: 'cache-2', to: 'db-replica-1' },
  { id: 'cache3-r2', from: 'cache-3', to: 'db-replica-2' },
  // Async replication from primary to replicas (vertical)
  { id: 'dbp-r1', from: 'db-primary', to: 'db-replica-1' },
  { id: 'dbp-r2', from: 'db-primary', to: 'db-replica-2' },
]

// Stage 5: DB Bottleneck → Cache Layer → Cache Failure → Cache Cluster
export const stage5: Stage = {
  id: 'stage-7',
  title: 'DB & Cache',
  subtitle: 'DB Bottleneck → Cache → Cache Failure → Redis Cluster',
  insight: '3 servers hammer DB. Add cache. Cache fails. Add cluster.',
  displayTitle: 'Database & Cache Layer',
  description: '3 servers saturate DB. Add cache layer. Then experience cache failure. Finally: Redis Cluster.',
  components: ['Client', 'API Gateway', 'Load Balancer', 'Server ×3', 'Cache ×3', 'Session Store', 'Database'],
  infoCard: {
    technicalTerm: 'Database Connection Pool Exhaustion',
    whenHappens: '10K+ RPS with multiple servers all querying the same database.',
    whatCondition: 'All 3 servers hit DB simultaneously. Pool climbs to 95%. Latency spikes 45ms→250ms. DB is the bottleneck.',
    howToResolve: 'Add Redis cache. 80% of reads are hot data — cache eliminates 80% of DB queries instantly.',
  },
  fixModes: [
    {
      // Fix 1: Add cache layer
      nodes: cacheNodes,
      edges: cacheEdges,
      viewBox: cacheViewBox,
      engineId: 'stage-cache-layer',
      enterLabel: 'Add Cache Layer',
      description: 'Redis cache added. 80% reads from cache. DB pool drops to 25%. Latency 35ms.',
      whatCondition: '10K RPS. 80% cache hits served in <5ms. Only 20% reach DB. Pool drops 95%→25%.',
      howToResolve: 'Cache works — but single node is a failure point. One crash floods the DB. Click to simulate.',
    },
    {
      // Fix 2: Cache node failure — hit rate degrades
      nodes: cacheNodes,
      edges: cacheEdges,
      viewBox: cacheViewBox,
      engineId: 'stage-9',
      enterLabel: 'Simulate Cache Failure',
      description: 'Cache-2 node dies. Hit rate degrades 80%→40%. DB overwhelmed again.',
      technicalTerm: 'Cache Node Failure / Cache Stampede',
      whenHappens: 'Cache nodes are in-memory. Without redundancy, a single failure floods the database.',
      whatCondition: 'Cache-2 fails (red X). Hit rate drops 80%→40%. DB pool spikes back to 85%.',
      howToResolve: 'Use Redis Cluster. Keys distributed with replicas — one loss ≈ 33% miss rate, not 50%. Auto-recovery.',
    },
    {
      // Fix 3: Redis Cluster — resilient final state
      nodes: cacheClusterNodes,
      edges: cacheEdges,
      viewBox: cacheViewBox,
      engineId: 'stage-cache-cluster',
      enterLabel: 'Add Redis Cluster',
      description: 'Redis Cluster with replication. Node failure only affects 33% of keys. Auto-recovery.',
      technicalTerm: 'Redis Cluster with Replication',
      whenHappens: 'At scale, cache becomes critical. Node failure must not degrade performance.',
      whatCondition: '10K RPS. 3 cluster nodes with replication. Hit rate stable at 85%. DB pool stays at 18%.',
      howToResolve: 'Redis Cluster + replication factor 2 is production standard. Eliminates cache as single failure domain.',
    },
  ],
  nodes: [
    { id: 'client', label: 'Client', type: 'client', x: 80, y: 220 },
    { id: 'api-gateway', label: 'API Gateway', type: 'api-gateway', x: 280, y: 220 },
    { id: 'load-balancer', label: 'Load Balancer', type: 'load-balancer', x: 460, y: 220 },
    { id: 'server-1', label: 'Server 1', type: 'server', x: 650, y: 110 },
    { id: 'server-2', label: 'Server 2', type: 'server', x: 650, y: 220 },
    { id: 'server-3', label: 'Server 3', type: 'server', x: 650, y: 330 },
    { id: 'session-store', label: 'Session Store', type: 'session-store', x: 850, y: 390 },
    { id: 'database', label: 'Database', type: 'database', x: 1050, y: 220 },
  ],
  edges: [
    { id: 'client-gw', from: 'client', to: 'api-gateway' },
    { id: 'gw-lb', from: 'api-gateway', to: 'load-balancer' },
    { id: 'lb-s1', from: 'load-balancer', to: 'server-1' },
    { id: 'lb-s2', from: 'load-balancer', to: 'server-2' },
    { id: 'lb-s3', from: 'load-balancer', to: 'server-3' },
    { id: 's2-store', from: 'server-2', to: 'session-store' },
    { id: 's1-db', from: 'server-1', to: 'database' },
    { id: 's2-db', from: 'server-2', to: 'database' },
    { id: 's3-db', from: 'server-3', to: 'database' },
  ],
  viewBox: '0 0 1220 450',
}

// Stage 6: Data Replication
export const stage6: Stage = {
  id: 'stage-10',
  title: 'Data Replication',
  subtitle: 'DB Bottleneck → Primary + Read Replicas',
  insight: 'Even with cache, single DB fails at 15K RPS. Replication solves it.',
  displayTitle: 'Database Replication',
  description: '15K RPS overwhelms single DB despite 85% cache hit rate. Add Primary + Read Replicas for full resilience.',
  components: ['Client', 'API Gateway', 'Load Balancer', 'Server ×3', 'Redis Cluster', 'Session Store', 'DB Primary', 'DB Replicas ×2'],
  infoCard: {
    technicalTerm: 'Single Database Bottleneck / Write Amplification',
    whenHappens: 'At 15K RPS, writes and cache misses (2,250+ q/s) overwhelm a single DB. Writes cannot be cached.',
    whatCondition: 'Pool hits 100%. Latency spikes to 800ms. Hit rate degrades 85%→62%. Error rate 5%.',
    howToResolve: 'Add read replicas: Primary handles writes, Replicas handle reads. Load distributed across 3 DB nodes.',
  },
  fixModes: [
    {
      nodes: dbReplicationNodes,
      edges: dbReplicationEdges,
      viewBox: replicaViewBox,
      engineId: 'stage-db-replica',
      enterLabel: 'Add DB Replication',
      description: 'Primary DB for writes. 2 Read Replicas for reads. Async replication. Pool drops to 18%.',
      technicalTerm: 'Primary-Replica Database Replication',
      whenHappens: 'Read traffic overwhelms a single DB. Separate writes (Primary) from reads (Replicas).',
      whatCondition: 'Writes → Primary. Cache misses → Replicas. Pool drops 100%→18%. Latency 800ms→28ms. Zero errors.',
      howToResolve: 'Primary handles writes only. Replicas handle reads. Async replication keeps them in sync.',
    },
  ],
  nodes: cacheClusterNodes,
  edges: cacheEdges,
  viewBox: replicaViewBox,
}

// Stage 7: Redis Key-Value Store
export const stageRedis: Stage = {
  id: 'stage-redis-kv',
  title: 'Redis Key-Value Store',
  subtitle: 'Hash Table + LRU Cache — Volatile vs Persistent',
  insight: 'Data stored in RAM only. Crash = total loss. Persistence modes protect data.',
  displayTitle: 'Redis KV Store Internals',
  description: 'Hash table with LRU eviction. See how persistence modes (RDB/AOF) prevent data loss.',
  components: ['Client', 'Redis', 'Hash Table', 'LRU List', 'Disk'],
  moduleType: 'redis-kv',
  infoCard: {
    technicalTerm: 'Redis Hash Table + LRU Eviction',
    whenHappens: 'Every SET writes to RAM. LRU evicts oldest entry when capacity exceeded. GET checks key.',
    whatCondition: 'No persistence: crash = complete data loss. RDB: snapshot to disk (periodic). AOF: write log (full recovery).',
    howToResolve: 'Enable persistence. RDB for snapshots (fast recovery, some loss), AOF for durability (replay all writes).',
  },
  fixModes: [
    {
      engineId: 'redis-rdb',
      enterLabel: 'Enable RDB',
      description: 'RDB snapshots — periodic backups to disk. Faster, but lose writes since last snapshot.',
      nodes: [], edges: [], viewBox: '0 0 1200 600',
      whatCondition: 'RDB snapshot saves all data to dump.rdb. On crash, replay from last snapshot. Data since snapshot is lost.',
      howToResolve: 'RDB is fast recovery. Trade: data loss window = time since last snapshot (~30 seconds in production).',
    },
    {
      engineId: 'redis-aof',
      enterLabel: 'Enable AOF',
      description: 'AOF (Append-Only File) — log every write. Full recovery but slower.',
      nodes: [], edges: [], viewBox: '0 0 1200 600',
      whatCondition: 'AOF appends every SET command to appendonly.aof. On crash, replay entire log = full recovery (or near-full).',
      howToResolve: 'AOF is durable. Trade: write amplification — every SET is a disk write. Can use fsync=everysec for balance.',
    },
  ],
  nodes: [],
  edges: [],
  viewBox: '0 0 1200 600',
}

export const stageLSM: Stage = {
  id: 'stage-lsm',
  title: 'Cassandra LSM Tree',
  subtitle: 'Log-Structured Merge Tree — Write Path, Compaction, Bloom Filters',
  insight: 'Memtable → L0 SSTables → L1. Bloom filters speed up reads. Compaction removes duplicates.',
  displayTitle: 'Cassandra LSM Tree Internals',
  description: 'Write-Ahead Log, in-memory Memtable, immutable SSTables, Bloom filters, compaction.',
  components: ['Client', 'Cassandra', 'WAL', 'Memtable', 'SSTables', 'Disk'],
  moduleType: 'lsm',
  infoCard: {
    technicalTerm: 'LSM Tree (Memtable + SSTables)',
    whenHappens: 'Every SET goes to WAL + Memtable. Memtable flush creates immutable SSTable. Compaction merges SSTables.',
    whatCondition: 'Memtable capacity exceeded → flush to L0. L0 accumulates SSTables → compaction to L1. Bloom filters skip SSTable checks on misses.',
    howToResolve: 'Flush often (keep Memtable small). Compact SSTables (reduces read amplification). Bloom filters eliminate false seeks.',
  },
  fixModes: [
    {
      engineId: 'lsm-bloom',
      enterLabel: 'Bloom Filter Optimization',
      description: 'Bloom filters allow quick negative lookups without SSTable access',
      nodes: [],
      edges: [],
      viewBox: '0 0 1200 580',
      whatCondition: 'GET checks Memtable, then L0/L1 SSTables. Bloom filter says "no" → skip; "maybe" → check entries.',
      howToResolve: 'Bloom filter reduces disk seeks on key misses. Probabilistic false positives acceptable.',
    },
    {
      engineId: 'lsm-compaction',
      enterLabel: 'Compaction Strategy',
      description: 'Compaction merges SSTables, removing duplicate keys and tombstones',
      nodes: [],
      edges: [],
      viewBox: '0 0 1200 580',
      whatCondition: 'L0 accumulates many SSTables. Compaction merges into L1, keeping newest version of each key.',
      howToResolve: 'Compaction reduces read amplification but increases write amplification. Balance with flush rate.',
    },
  ],
  nodes: [],
  edges: [],
  viewBox: '0 0 1200 580',
}

export const stageBTree: Stage = {
  id: 'stage-btree',
  title: 'PostgreSQL B+ Tree',
  subtitle: 'B+ Tree Index — Insert, Split, Range Scan',
  insight: 'B+ Tree maintains sorted keys. Leaf chain enables O(K) range scans. Splits rebalance the tree.',
  displayTitle: 'PostgreSQL B+ Tree Internals',
  description: 'Watch a B+ Tree index grow. See page splits, leaf linking, and efficient range scans.',
  components: ['Client', 'PostgreSQL', 'B+ Tree Index', 'Heap'],
  moduleType: 'btree',
  infoCard: {
    technicalTerm: 'B+ Tree Index',
    whenHappens: 'Every INSERT updates the B+ Tree. Index lookup uses tree traversal. Range queries scan leaf chain.',
    whatCondition: 'Leaf page overflow (> 3 keys) triggers split. Median key pushed to parent. Parent may overflow → root split → height increases.',
    howToResolve: 'Splits are O(log N) amortized. Leaf chain enables O(K) range scans. Tree stays balanced automatically.',
  },
  fixModes: [
    {
      engineId: 'btree-search',
      enterLabel: 'Efficient Range Scan',
      description: 'Leaf chain enables O(K) range scan without re-traversing tree',
      nodes: [],
      edges: [],
      viewBox: '0 0 1100 560',
      whatCondition: 'Range query [lo, hi] finds leftmost matching leaf, scans right via leaf links.',
      howToResolve: 'Leaf chain = O(results) scan. No re-traversal needed. Efficient for range queries.',
    },
  ],
  nodes: [],
  edges: [],
  viewBox: '0 0 1100 560',
}

export const stageTransformer: Stage = {
  id: 'stage-transformer',
  title: 'LLM Transformer',
  subtitle: 'GPT Decoder — Attention, FFN, Next Token Prediction',
  insight: 'Tokenize → embed → 2 attention layers → softmax → predict next token.',
  displayTitle: 'Transformer Inference Engine',
  description: 'See how a GPT-style decoder predicts the next token step by step.',
  components: ['Tokenizer', 'Embedding', 'Multi-Head Attention', 'FFN', 'Softmax', 'Sampler'],
  moduleType: 'transformer',
  infoCard: {
    technicalTerm: 'Decoder-Only Transformer (GPT Architecture)',
    whenHappens: 'Every LLM token generation: text → tokens → embeddings → layers → probabilities → sample.',
    whatCondition: 'Input tokenized (word split). Each token → 8-dim vector. 2 layers apply self-attention + FFN. Last token hidden state projected to 20-word vocab logits.',
    howToResolve: 'Type a sentence, click RUN FORWARD. Use fix modes to zoom into Attention, FFN, or Prediction/Temperature.',
  },
  fixModes: [
    {
      engineId: 'transformer-attention',
      enterLabel: 'Attention Deep Dive',
      description: 'Q/K/V matrices, causal mask, and attention heatmap',
      nodes: [],
      edges: [],
      viewBox: '0 0 1200 600',
      technicalTerm: 'Multi-Head Self-Attention (MHSA)',
      whenHappens: 'Every layer. Each token attends all prior tokens. Causal mask blocks future.',
      whatCondition: 'Q×Kᵀ/√d_k → causal mask → softmax → ×V → concat heads → project.',
      howToResolve: 'More heads = richer representations. 1/√d scaling stabilises gradients.',
    },
    {
      engineId: 'transformer-ffn',
      enterLabel: 'FFN Deep Dive',
      description: '4× expansion, GELU activation, projection back',
      nodes: [],
      edges: [],
      viewBox: '0 0 1200 600',
      technicalTerm: 'Feed-Forward Network (FFN) with GELU',
      whenHappens: 'After attention in every layer. Applied independently per token position.',
      whatCondition: 'W1 expands 8→32. GELU non-linearity. W2 projects 32→8. Residual added.',
      howToResolve: 'FFN = pattern memory. GELU smoother than ReLU. 4× expansion is standard.',
    },
    {
      engineId: 'transformer-predict',
      enterLabel: 'Prediction Step',
      description: 'Logits, softmax, temperature, top-5 predictions',
      nodes: [],
      edges: [],
      viewBox: '0 0 1200 600',
      technicalTerm: 'Unembedding + Softmax Sampling',
      whenHappens: 'After final layer. Last token hidden state → vocabulary probabilities.',
      whatCondition: '8-dim hidden × 8×20 unembedding = 20 logits. Softmax(logits/τ) = probs.',
      howToResolve: 'τ<1 = sharp/deterministic. τ>1 = flat/random. Greedy = argmax.',
    },
  ],
  nodes: [],
  edges: [],
  viewBox: '0 0 1200 600',
}

export const stageTCP: Stage = {
  id: 'stage-tcp',
  title: 'TCP Handshake',
  subtitle: '3-Way Handshake — SYN, SYN-ACK, ACK',
  insight: 'TCP establishes connections via a 3-way handshake: SYN → SYN-ACK → ACK. Each side confirms sequence numbers.',
  displayTitle: 'TCP 3-Way Handshake',
  description: 'Watch TCP establish, use, and close connections. See SYN/ACK packets flow between client and server.',
  components: ['Client', 'Server', 'SYN', 'ACK', 'FIN', 'RST'],
  moduleType: 'tcp',
  learningObjective: 'Understand how TCP turns packet exchange into connection state before application data is sent.',
  misconception: 'TCP does not instantly connect when a client calls connect(); the OS must observe packet responses and update socket state.',
  interviewTakeaway: 'Explain TCP as a state machine: SYN opens intent, SYN-ACK proves the server is reachable, ACK confirms both sides can send and receive.',
  steps: [
    { title: 'SYN', description: 'Client proposes a connection and sequence number.', stateLabel: 'client=SYN_SENT', outputLabel: 'packet leaves client' },
    { title: 'SYN-ACK', description: 'Server accepts and replies with its own sequence number.', stateLabel: 'server=SYN_RECEIVED', outputLabel: 'server reachable' },
    { title: 'ACK', description: 'Client acknowledges the server sequence.', stateLabel: 'ESTABLISHED', outputLabel: 'data can flow' },
  ],
  infoCard: {
    technicalTerm: 'TCP 3-Way Handshake',
    whenHappens: 'Every TCP connection: HTTP requests, database connections, SSH sessions. Before any data can flow.',
    whatCondition: 'Client sends SYN (seq=X). Server responds SYN-ACK (seq=Y, ack=X+1). Client sends ACK (ack=Y+1). Connection established.',
    howToResolve: 'Handshake ensures both sides agree on sequence numbers and are ready. Takes 1 RTT before data flows.',
  },
  fixModes: [
    {
      engineId: 'tcp-timeout',
      enterLabel: 'SYN Timeout & Retry',
      description: 'Server unreachable — client retries with exponential backoff',
      nodes: [], edges: [], viewBox: '0 0 1100 580',
      technicalTerm: 'TCP SYN Timeout & Exponential Backoff',
      whenHappens: 'Server is down, firewall drops packets, or network is unreachable. SYN gets no response.',
      whatCondition: 'Client waits for SYN-ACK. Timeout triggers retry: 1s → 2s → 4s → 8s (exponential backoff). Typically 3-5 retries before giving up.',
      howToResolve: 'OS kernel handles retries automatically. Application sees ETIMEDOUT after all retries exhausted.',
    },
    {
      engineId: 'tcp-rst',
      enterLabel: 'Connection Reset (RST)',
      description: 'Server rejects connection — port closed or service unavailable',
      nodes: [], edges: [], viewBox: '0 0 1100 580',
      technicalTerm: 'TCP RST (Connection Reset)',
      whenHappens: 'Client SYNs to a closed port, crashed service, or firewall that actively rejects.',
      whatCondition: 'Server sends RST packet instead of SYN-ACK. Connection immediately fails. No retries — port is definitely closed.',
      howToResolve: 'RST = fast fail. Check if service is running, port is correct, firewall rules allow traffic.',
    },
    {
      engineId: 'tcp-close',
      enterLabel: 'Connection Close & TIME-WAIT',
      description: 'Graceful close via FIN/ACK and the 2×MSL TIME-WAIT state',
      nodes: [], edges: [], viewBox: '0 0 1100 580',
      technicalTerm: 'TCP Connection Termination & TIME-WAIT',
      whenHappens: 'Application calls close(). Initiator sends FIN, receiver ACKs, sends its own FIN, gets final ACK.',
      whatCondition: '4-way close: FIN → ACK → FIN → ACK. Initiator enters TIME-WAIT for 2×MSL (60-120s) to handle delayed packets.',
      howToResolve: 'TIME-WAIT prevents old packets from corrupting new connections on same port. SO_REUSEADDR can help in development.',
    },
  ],
  nodes: [],
  edges: [],
  viewBox: '0 0 1100 580',
}

export const stageKafka: Stage = {
  id: 'stage-kafka',
  title: 'Apache Kafka',
  subtitle: 'Message Broker — From Simple Queue to Distributed System',
  insight: 'Start simple: producer → log → consumer. Then add partitions, replication, and scaling.',
  displayTitle: 'Kafka Message Broker',
  description: 'Build understanding of Kafka step by step — from a simple log to a distributed fault-tolerant system.',
  components: ['Producer', 'Topic Log', 'Consumer', 'Partitions', 'Brokers'],
  moduleType: 'kafka',
  learningObjective: 'Follow one message from producer input through routing, append, durability, and consumer offset movement.',
  misconception: 'Kafka is not just a queue that deletes messages after read; it is a retained log where consumers track offsets.',
  interviewTakeaway: 'Kafka scaling comes from partitioned logs, while reliability comes from leader/follower replication and committed offsets.',
  steps: [
    { title: 'Produce', description: 'Producer creates a keyed record.', stateLabel: 'record key/value', outputLabel: 'send to topic' },
    { title: 'Route', description: 'Partitioner maps key to a partition.', stateLabel: 'hash(key) % partitions', outputLabel: 'target partition' },
    { title: 'Append', description: 'Leader appends record and advances log end offset.', stateLabel: 'LEO/HWM', outputLabel: 'record committed' },
    { title: 'Consume', description: 'Consumer reads by offset and advances position.', stateLabel: 'group offset', outputLabel: 'lag changes' },
  ],
  infoCard: {
    technicalTerm: 'Append-Only Commit Log',
    whenHappens: 'Every message system. Producers write messages, consumers read by offset position.',
    whatCondition: 'Messages appended sequentially to a log. Consumer tracks its position via offset. Messages persist — not deleted when read.',
    howToResolve: 'Produce messages, watch offsets increment. Consume to advance the consumer position. Messages stay in the log.',
  },
  fixModes: [
    {
      engineId: 'kafka-partitions',
      enterLabel: 'Add Partitions',
      description: 'Split topic into 3 partitions — hash(key) determines routing',
      nodes: [], edges: [], viewBox: '0 0 1000 400',
      technicalTerm: 'Partition Key Hashing',
      whenHappens: 'Topic created with N partitions. Each message\'s key is hashed to determine which partition receives it.',
      whatCondition: 'hash(key) % partition_count = target partition. Same key ALWAYS maps to same partition. Ordering guaranteed per partition, NOT across partitions.',
      howToResolve: 'Try producing with the same key multiple times — always hits the same partition. Try different keys — they spread across partitions. That\'s parallelism + ordering.',
    },
    {
      engineId: 'kafka-replication',
      enterLabel: 'Add Replication',
      description: 'Brokers appear — each partition gets a leader + follower replica',
      nodes: [], edges: [], viewBox: '0 0 1200 460',
      technicalTerm: 'In-Sync Replicas (ISR)',
      whenHappens: 'Every write. Leader receives message, followers fetch to replicate. ISR = set of caught-up replicas.',
      whatCondition: 'acks=1: leader acknowledges immediately (fast but risky). acks=all: waits for ALL ISR members (safe but slower). HWM = what consumers can read.',
      howToResolve: 'Toggle acks mode and watch the difference. acks=all: LEO advances but HWM lags until replication completes. acks=1: both advance instantly.',
    },
    {
      engineId: 'kafka-failure',
      enterLabel: 'Broker Failure',
      description: 'Kill a broker — watch leader election and ISR changes',
      nodes: [], edges: [], viewBox: '0 0 1200 500',
      technicalTerm: 'Partition Leader Election',
      whenHappens: 'Leader broker dies. Controller detects via heartbeat timeout. Elects new leader from surviving ISR members.',
      whatCondition: 'Dead broker removed from ISR. First alive ISR member becomes new leader. If NO ISR member alive → partition unavailable (produce fails).',
      howToResolve: 'Start auto-produce, then kill a broker. Watch: partition briefly unavailable → new leader elected → production resumes. Replication factor > 1 is why this works.',
    },
    {
      engineId: 'kafka-consumers',
      enterLabel: 'Consumer Groups',
      description: 'Scale consumption — add consumers, watch partition rebalancing',
      nodes: [], edges: [], viewBox: '0 0 1200 500',
      technicalTerm: 'Consumer Group Rebalancing',
      whenHappens: 'Consumer joins, leaves, or crashes. Group coordinator triggers rebalance across ALL consumers in the group.',
      whatCondition: 'ALL consumers STOP consuming. Partitions redistributed (round-robin). ALL consumers resume with new assignments. Brief unavailability.',
      howToResolve: 'Add a consumer → watch rebalancing pause everything → partitions redistribute. 3 partitions + 3 consumers = 1 each (max parallelism).',
    },
  ],
  nodes: [],
  edges: [],
  viewBox: '0 0 1000 400',
}

export const stageRateLimiter: Stage = {
  id: 'stage-rate-limiter',
  title: 'Rate Limiting',
  subtitle: 'Token Bucket, Sliding Window, Fixed Window, Leaky Bucket',
  insight: 'A rate limiter makes a per-request decision before the backend ever sees the request.',
  displayTitle: 'API Gateway Rate Limiting',
  description: 'Watch how the gateway identifies a caller, reads stored request state, compares the threshold, then forwards, queues, or returns 429.',
  components: ['Client', 'API Gateway Rate Limiter', 'Request State Store', 'Backend'],
  moduleType: 'rate-limiter',
  learningObjective: 'See how a gateway makes one per-request decision from caller identity, stored state, threshold rule, and action.',
  misconception: 'A limiter does not randomly block aggregate traffic; it usually evaluates a specific key such as user, API key, IP, route, or tenant.',
  interviewTakeaway: 'Rate limiting is a fast read-update-write decision at the edge: derive key, fetch state, compare rule, mutate state, then allow, queue, or reject with 429.',
  steps: [
    { title: 'Identify', description: 'Derive the rate-limit key from caller and route.', stateLabel: 'key=user/IP/API route', outputLabel: 'state bucket selected' },
    { title: 'Lookup', description: 'Read only that key’s limiter state.', stateLabel: 'tokens/log/counter/queue', outputLabel: 'current usage known' },
    { title: 'Compare', description: 'Apply the algorithm threshold.', stateLabel: 'limit rule', outputLabel: 'allow/deny decision' },
    { title: 'Act', description: 'Forward, queue, or reject this request.', stateLabel: 'state updated', outputLabel: 'HTTP 200/queued/429' },
  ],
  infoCard: {
    technicalTerm: 'Unprotected API Traffic',
    whenHappens: 'Every request is forwarded directly to the backend. The gateway does not identify the caller, record recent calls, or enforce any threshold.',
    whatCondition: 'A burst from one IP, API key, user, or route is indistinguishable from healthy traffic. The backend CPU absorbs all of it, latency rises, then the service can crash.',
    howToResolve: 'Put the decision at the gateway: derive a key, read that key\'s rate-limit state, compare the rule, then either forward, queue, or return HTTP 429 before the backend is touched.',
  },
  fixModes: [
    {
      engineId: 'rl-token-bucket',
      enterLabel: 'Token Bucket',
      description: 'Gateway reads a token balance for this caller. One request spends one token.',
      nodes: [], edges: [], viewBox: '0 0 900 420',
      technicalTerm: 'Token Bucket Algorithm',
      whenHappens: 'The gateway stores a token bucket per key, often IP + user/API key + route. On each request it reads the bucket, then decides immediately.',
      whatCondition: 'If the bucket has at least 1 token, the gateway consumes it and forwards the request. If the bucket is empty, this exact request is rejected with HTTP 429.',
      howToResolve: 'Use this when you want simple O(1) state with controlled bursts. Idle time refills tokens, but capacity caps how large a burst can get.',
    },
    {
      engineId: 'rl-sliding-window-log',
      enterLabel: 'Sliding Window Log',
      description: 'Gateway stores exact timestamps for this caller and counts the active window.',
      nodes: [], edges: [], viewBox: '0 0 900 420',
      technicalTerm: 'Sliding Window Log',
      whenHappens: 'Every accepted request appends a timestamp to that key\'s log. Before checking the next request, old timestamps outside the window are pruned.',
      whatCondition: 'If the remaining timestamp count is below the limit, the request is allowed and its timestamp is recorded. If the count is already full, the request gets 429.',
      howToResolve: 'Use this when exact fairness matters. It is easy to understand but stores one timestamp per request, so memory grows with traffic.',
    },
    {
      engineId: 'rl-fixed-window',
      enterLabel: 'Fixed Window',
      description: 'Gateway stores one counter for this caller inside the current time box.',
      nodes: [], edges: [], viewBox: '0 0 900 420',
      technicalTerm: 'Fixed Window Counter',
      whenHappens: 'Time is divided into fixed windows. The gateway reads the current window counter for the key, increments it, then compares it to the limit.',
      whatCondition: 'It is fast and tiny in memory, but the boundary reset can allow too many requests: a caller can spend the end of one window and the start of the next back to back.',
      howToResolve: 'Try TRIGGER BURST. It demonstrates why simple counters are easy to operate but can be unfair near window boundaries.',
    },
    {
      engineId: 'rl-sliding-window-counter',
      enterLabel: 'Sliding Window Counter',
      description: 'Gateway estimates current load from previous and current counters.',
      nodes: [], edges: [], viewBox: '0 0 900 420',
      technicalTerm: 'Sliding Window Counter',
      whenHappens: 'The gateway keeps two counters for the key: previous window and current window. It weights the previous count down as time moves forward.',
      whatCondition: 'The request is allowed only while the weighted estimate is below the threshold. This avoids the harsh reset problem without storing every timestamp.',
      howToResolve: 'Use this when you need O(1) state with smoother behavior than fixed windows. Watch the formula explain why a request is allowed or 429ed.',
    },
    {
      engineId: 'rl-leaky-bucket',
      enterLabel: 'Leaky Bucket',
      description: 'Gateway queues requests and drains them to the backend at a fixed rate.',
      nodes: [], edges: [], viewBox: '0 0 900 420',
      technicalTerm: 'Leaky Bucket (Queue-Based)',
      whenHappens: 'Each request checks whether the queue for this traffic class has space. If yes, it waits. If no, the gateway returns 429 immediately.',
      whatCondition: 'This protects the backend with a smooth output rate, but accepted requests may wait in the queue. Full queue means overflow.',
      howToResolve: 'Use this when constant backend throughput matters more than burst friendliness. It teaches the difference between rejecting now and delaying safely.',
    },
  ],
  nodes: [],
  edges: [],
  viewBox: '0 0 900 420',
}

export const stageShazam: Stage = {
  id: 'stage-shazam',
  title: 'Shazam Fingerprinting',
  subtitle: 'Spectrogram → Peaks → Hash Pairs → Histogram Match',
  insight: 'Shazam identifies songs in seconds by matching sparse spectral peaks, not raw audio.',
  displayTitle: 'Audio Fingerprinting (Shazam)',
  description: 'See how Shazam converts audio into a spectrogram, extracts peaks, hashes anchor-target pairs, and matches via time-offset histograms.',
  components: ['Audio', 'Spectrogram', 'Constellation', 'Hash Table', 'Histogram'],
  moduleType: 'shazam',
  infoCard: {
    technicalTerm: 'Audio Waveform',
    whenHappens: 'Raw audio is just amplitude over time — a continuous wave signal sampled at 44.1 kHz.',
    whatCondition: 'Matching raw waveforms is impractical: noise, volume, and timing variations make direct comparison fail.',
    howToResolve: 'Transform audio into a frequency-domain representation (spectrogram) to reveal the underlying structure. Apply each fix mode to see the pipeline.',
  },
  fixModes: [
    {
      engineId: 'shazam-spectrogram',
      enterLabel: 'Spectrogram (STFT)',
      description: 'Convert waveform to time-frequency grid via Short-Time Fourier Transform',
      nodes: [], edges: [], viewBox: '0 0 900 380',
      technicalTerm: 'Short-Time Fourier Transform (STFT)',
      whenHappens: 'Audio is split into overlapping windows (~23ms each). FFT is applied to each window, producing frequency amplitudes.',
      whatCondition: 'The spectrogram reveals WHICH frequencies are loud at WHICH time. Color = energy intensity. Each column is one FFT window.',
      howToResolve: 'Watch the spectrogram build left-to-right as time windows are processed. Bright regions = loud frequencies = the song\'s signature.',
    },
    {
      engineId: 'shazam-constellation',
      enterLabel: 'Constellation Map',
      description: 'Extract spectral peaks — local maxima in time-frequency space',
      nodes: [], edges: [], viewBox: '0 0 900 380',
      technicalTerm: 'Spectral Peak Extraction',
      whenHappens: 'Each spectrogram cell is compared to its 8 neighbors. If it\'s the local maximum AND above threshold → it\'s a peak.',
      whatCondition: 'Peaks are the "essence" of the audio. 320,000 data points → ~50 peaks. These peaks survive noise because they represent the loudest, most stable features.',
      howToResolve: 'Adjust the threshold slider. Lower = more peaks (more detail but more noise). Higher = fewer peaks (cleaner but might miss features). The sparse constellation IS the fingerprint.',
    },
    {
      engineId: 'shazam-hashing',
      enterLabel: 'Fingerprint Hashing',
      description: 'Pair peaks as anchor + target → combinatorial hash (f₁, f₂, Δt)',
      nodes: [], edges: [], viewBox: '0 0 900 380',
      technicalTerm: 'Combinatorial Hashing',
      whenHappens: 'Each peak becomes an anchor. It pairs with nearby peaks in a target zone (ahead in time, ±4 frequency bins). Hash = (f₁, f₂, Δt).',
      whatCondition: 'Single peaks are not unique enough — many songs share frequency X. But the PAIR (f₁=440, f₂=880, Δt=3) is almost unique. This is Shazam\'s key insight.',
      howToResolve: 'Watch anchors cycle through their target zones. Each pair produces a 32-bit hash. Fan-out of ~5 targets per anchor creates ~250 hashes from ~50 peaks.',
    },
    {
      engineId: 'shazam-matching',
      enterLabel: 'Database Lookup',
      description: 'Look up query hashes against 5 songs — find which songs share hashes',
      nodes: [], edges: [], viewBox: '0 0 900 380',
      technicalTerm: 'Hash Table Lookup',
      whenHappens: 'Query audio is fingerprinted the same way. Each query hash is looked up in the database. Multiple songs may match some hashes by coincidence.',
      whatCondition: 'Matching hashes alone is NOT enough — random collisions produce false matches. We need to check TIME COHERENCY to confirm.',
      howToResolve: 'Watch hash lookups accumulate matches per song. Several songs have some matching hashes. But which one is the REAL match? The next step reveals how.',
    },
    {
      engineId: 'shazam-histogram',
      enterLabel: 'Time Coherency',
      description: 'Build time-offset histograms — true match produces a spike',
      nodes: [], edges: [], viewBox: '0 0 900 380',
      technicalTerm: 'Time-Offset Histogram',
      whenHappens: 'For each matching hash: compute offset = query_time - db_time. If all matches align to the SAME offset → the song is a true match.',
      whatCondition: 'True match: histogram spike at one offset (all hashes agree on timing). False match: hashes scatter across random offsets (no coherency). THIS is the magic.',
      howToResolve: 'Watch histograms build for each candidate song. One song produces a dramatic spike — that\'s the match. Others stay flat. Time coherency = audio recognition.',
    },
  ],
  nodes: [],
  edges: [],
  viewBox: '0 0 900 380',
}

export const stageSharding: Stage = {
  id: 'stage-sharding',
  title: 'Sharding vs Partitioning',
  subtitle: 'Same Hash, Two Architectures — Side-by-Side',
  insight: 'Partitioning splits one logical table inside ONE server. Sharding splits it across MANY independent servers. Same hash, very different consequences.',
  displayTitle: 'Sharding vs Partitioning',
  description: 'Watch the same keys, same queries, same hash function — running on one node (partitioning) and on N nodes (sharding) at the same time. The split-screen reveals where they diverge: network cost, blast radius, transactions.',
  components: ['Client', 'Query Planner', 'Shard Router', 'Partitions ×4', 'Shards ×4'],
  moduleType: 'sharding',
  infoCard: {
    technicalTerm: 'Partitioning vs Sharding — Topology',
    whenHappens: 'Any data store that grows beyond a single-table or single-node limit. Both strategies divide rows by key, but at very different layers.',
    whatCondition: 'Partitioning: one DB process splits one logical table into chunks (range/list/hash). Sharding: many DB processes, each owns a key range; routing is external (app or proxy).',
    howToResolve: 'Pick a fix mode to compare the two on writes, point reads, range scans, failure, and cross-key transactions. Same input → two very different behaviors.',
  },
  fixModes: [
    {
      engineId: 'sharding-writes',
      enterLabel: 'Writes — Hash & Place',
      description: 'Insert keys. Same hash function, very different transport: function call vs network RTT.',
      nodes: [], edges: [], viewBox: '0 0 1400 620',
      technicalTerm: 'Hash-Based Placement',
      whenHappens: 'Each write: `hash(key) % N` selects a target. Both LEFT and RIGHT use the same function — the difference is what happens AFTER the hash.',
      whatCondition: 'LEFT: planner writes to a local partition (microseconds, no network). RIGHT: router writes to a remote shard over the network (~1 RTT per write, ~64B payload).',
      howToResolve: 'Insert keys one by one or auto-insert all. Watch the network-bytes counter climb on the right side while it stays at 0 on the left.',
    },
    {
      engineId: 'sharding-point',
      enterLabel: 'Point Read — One Key',
      description: 'SELECT WHERE id = K. Both prune to one bucket. Both are fast.',
      nodes: [], edges: [], viewBox: '0 0 1400 620',
      technicalTerm: 'Single-Key Lookup',
      whenHappens: 'Every key-based query (primary key lookup, cache fetch). The most common pattern in OLTP workloads.',
      whatCondition: 'LEFT: planner prunes to one partition (~0.5 ms). RIGHT: router maps to one shard, 1 network hop (~3 ms). Both are O(1) work, only the transport differs.',
      howToResolve: 'This is the sweet spot for sharding. If your workload is 99% single-key reads, sharding adds little overhead. Range scans and joins are where it gets expensive.',
    },
    {
      engineId: 'sharding-range',
      enterLabel: 'Range / Scatter Query',
      description: 'WHERE id BETWEEN lo AND hi. Sequential scan vs network fan-out.',
      nodes: [], edges: [], viewBox: '0 0 1400 620',
      technicalTerm: 'Scatter-Gather Range Scan',
      whenHappens: 'Any query that spans bucket boundaries: range queries, full-table scans, cross-key joins, analytics queries.',
      whatCondition: 'LEFT: one process scans 4 partitions on the same disk — sequential, ~4 ms total. RIGHT: router fans out to ALL 4 shards in parallel — 4 simultaneous RTTs + merge. Network is the new bottleneck.',
      howToResolve: 'This is the hidden cost of sharding. To avoid scatter-gather, design keys so related rows live on the same shard (co-location). Otherwise expect tail-latency from the slowest shard.',
    },
    {
      engineId: 'sharding-failure',
      enterLabel: 'Failure — Blast Radius',
      description: 'Kill the server vs kill one shard. Watch what survives.',
      nodes: [], edges: [], viewBox: '0 0 1400 620',
      technicalTerm: 'Independent Failure Domains',
      whenHappens: 'Hardware fails. Disks fail. OS crashes. Processes OOM. Pick your poison — eventually a node will die.',
      whatCondition: 'LEFT: one server failure = entire DB unavailable (all 4 partitions). RIGHT: one shard failure = only 1/4 of keys unavailable; the other 3 shards keep serving traffic.',
      howToResolve: 'This is why we shard at scale. Independent failure domains mean degraded service instead of total outage. Add replicas per shard to push the failure rate even lower.',
    },
    {
      engineId: 'sharding-txn',
      enterLabel: 'Atomic Transfer (2PC)',
      description: 'Update two keys atomically. ACID vs 2-Phase Commit.',
      nodes: [], edges: [], viewBox: '0 0 1400 620',
      technicalTerm: 'Distributed Transactions (Two-Phase Commit)',
      whenHappens: 'Any operation that must atomically update keys that live on different shards: bank transfers, inventory moves, multi-row updates.',
      whatCondition: 'LEFT: one BEGIN/COMMIT on one server — one log write, one transaction manager, instant. RIGHT: coordinator runs 2PC — PREPARE (locks acquired), VOTE-YES, COMMIT, ACK. 4 network round-trips. Locks held the whole time.',
      howToResolve: 'Distributed transactions are slow AND complex (coordinator failures → orphan locks, recovery protocols). Most sharded systems avoid them entirely — use sagas, eventual consistency, or co-locate related keys on the same shard.',
    },
    {
      engineId: 'sharding-scale-wall',
      enterLabel: 'Scale Wall — Where Sharding Wins',
      description: 'Crank load. Watch the single server hit a wall while N shards stay flat.',
      nodes: [], edges: [], viewBox: '0 0 1400 620',
      technicalTerm: 'Vertical vs Horizontal Scaling Ceiling',
      whenHappens: 'Any workload that grows beyond one machine. The first 4 modes show sharding\'s costs (RTT, scatter, 2PC). This mode shows what you BUY for those costs: capacity that one box can\'t provide.',
      whatCondition: 'LEFT (one server): CPU climbs linearly with rps. Past ~80K rps CPU saturates → latency explodes (hockey stick) → errors. Disk fills → writes fail. Bigger box helps for a while, then there is no bigger box.',
      howToResolve: 'Push the LOAD slider to 100K rps and watch LEFT thrash. Then push to 200K — LEFT is at the wall, RIGHT shards are still at 50% CPU each. This is why sharding exists.',
    },
  ],
  nodes: [],
  edges: [],
  viewBox: '0 0 1400 620',
}

export const stages: Stage[] = [
  stage1,
  stage2,
  stage3,
  stage4,
  stage5,
  stage6,
  stageRedis,
  stageLSM,
  stageBTree,
  stageTransformer,
  stageTCP,
  stageKafka,
  stageRateLimiter,
  stageShazam,
  stageSharding,
]
