import type { Stage } from './types'

// Stage 1: Baseline
export const stage1: Stage = {
  id: 'stage-1',
  title: 'Baseline',
  subtitle: 'Single Server — Healthy Metrics',
  insight: 'Server at 15% CPU — comfortable headroom.',
  displayTitle: 'Baseline Architecture',
  description: 'Single server handling all traffic. Healthy metrics at low load.',
  components: ['Client', 'Server', 'Database'],
  infoCard: {
    technicalTerm: 'Monolithic Single-Server',
    whenHappens: 'Early in application development. Traffic is low and predictable. One server handles everything.',
    whatCondition: 'A single process serves web requests, runs business logic, and queries the database. No redundancy. At this stage, 100 RPS at 15% CPU is comfortable headroom.',
    howToResolve: 'This is the healthy baseline. Problems emerge when traffic grows. Subsequent stages show architectural issues and solutions.',
  },
  nodes: [
    { id: 'client', label: 'Client', type: 'client', x: 150, y: 200 },
    { id: 'server', label: 'Server', type: 'server', x: 450, y: 200 },
    { id: 'database', label: 'Database', type: 'database', x: 750, y: 200 },
  ],
  edges: [
    { id: 'client-server', from: 'client', to: 'server' },
    { id: 'server-db', from: 'server', to: 'database' },
  ],
  viewBox: '0 0 900 400',
}

// Stage 2: Stateful Auth with Fix
export const stage2: Stage = {
  id: 'stage-2',
  title: 'Stateful Auth',
  subtitle: 'In-Memory Auth — CPU Spikes at 5K RPS',
  insight: 'Server checks auth in-memory. CPU jumps to 75%.',
  displayTitle: 'Stateful Authentication Problem',
  description: 'Server stores session data in memory. Auth check runs in-process per request, causing CPU overhead.',
  components: ['Client', 'Server', 'Database'],
  infoCard: {
    technicalTerm: 'Stateful Server',
    whenHappens: 'When user auth data is held in server memory. Works fine with one server, breaks under load balancing or horizontal scaling.',
    whatCondition: 'Every incoming request triggers an in-memory session lookup on the server. At 5K RPS, this adds 30% CPU overhead. At 1M concurrent users, you cannot add servers without breaking auth.',
    howToResolve: 'Move session storage to Redis/Session Store. Server becomes stateless. Any replica handles any request. No sticky routing needed.',
  },
  fixModes: [
    {
      nodes: [
        { id: 'client', label: 'Client', type: 'client', x: 120, y: 220 },
        { id: 'server', label: 'Server', type: 'server', x: 420, y: 220 },
        { id: 'session-store', label: 'Session Store', type: 'session-store', x: 420, y: 360 },
        { id: 'database', label: 'Database', type: 'database', x: 820, y: 220 },
      ],
      edges: [
        { id: 'client-server', from: 'client', to: 'server' },
        { id: 'server-store', from: 'server', to: 'session-store' },
        { id: 'server-db', from: 'server', to: 'database' },
      ],
      viewBox: '0 0 1000 440',
      engineId: 'stage-3',
      enterLabel: 'Apply Fix: Go Stateless',
      description: 'Sessions offloaded to Redis. Server CPU drops to 45%. No sticky sessions needed.',
    },
  ],
  nodes: [
    { id: 'client', label: 'Client', type: 'client', x: 150, y: 200 },
    { id: 'server', label: 'Server', type: 'server', x: 450, y: 200 },
    { id: 'database', label: 'Database', type: 'database', x: 750, y: 200 },
  ],
  edges: [
    { id: 'client-server', from: 'client', to: 'server' },
    { id: 'server-db', from: 'server', to: 'database' },
  ],
  viewBox: '0 0 900 400',
}

// Stage 3: API Gateway & Rate Limiting (NEW)
export const stage3: Stage = {
  id: 'stage-api-gw',
  title: 'API Gateway',
  subtitle: 'Validate & Rate-Limit Incoming Requests',
  insight: 'Unfiltered traffic overwhelms servers. Gateway filters bad requests.',
  displayTitle: 'API Gateway & Rate Limiting',
  description: 'Protect servers from overload with validation, rate limiting, and request filtering.',
  components: ['Client', 'API Gateway', 'Server ×3', 'Database'],
  infoCard: {
    technicalTerm: 'API Gateway & Rate Limiting',
    whenHappens: 'When direct client-to-server communication allows bad actors, bots, and malformed requests to overwhelm servers.',
    whatCondition: '14K unfiltered RPS hit servers directly. No validation, no rate limiting. Servers receive bots and malformed requests. CPU spikes to 95%. Error rate climbs above 30%.',
    howToResolve: 'Add an API Gateway as the single entry point. It validates format, checks auth, enforces rate limits, and routes requests. Bad traffic never reaches application servers.',
  },
  fixModes: [
    {
      nodes: [
        { id: 'client', label: 'Client', type: 'client', x: 100, y: 220 },
        { id: 'server-1', label: 'Server 1', type: 'server', x: 400, y: 110 },
        { id: 'server-2', label: 'Server 2', type: 'server', x: 400, y: 220 },
        { id: 'server-3', label: 'Server 3', type: 'server', x: 400, y: 330 },
        { id: 'database', label: 'Database', type: 'database', x: 750, y: 220 },
      ],
      edges: [
        { id: 'client-s1', from: 'client', to: 'server-1' },
        { id: 'client-s2', from: 'client', to: 'server-2' },
        { id: 'client-s3', from: 'client', to: 'server-3' },
        { id: 's1-db', from: 'server-1', to: 'database' },
        { id: 's2-db', from: 'server-2', to: 'database' },
        { id: 's3-db', from: 'server-3', to: 'database' },
      ],
      viewBox: '0 0 900 440',
      engineId: 'stage-api-problem',
      enterLabel: 'Add API Gateway',
      description: 'Unfiltered traffic directly hitting servers. Servers overloaded, requests dropped.',
      whatCondition: '14K RPS hit 3 servers directly. No filtering. Each server at 95% CPU. Errors exceed 30%. Requests being dropped.',
      howToResolve: 'Add an API Gateway to filter requests, rate limit, validate, and protect servers.',
    },
    {
      nodes: [
        { id: 'client', label: 'Client', type: 'client', x: 80, y: 220 },
        { id: 'api-gateway', label: 'API Gateway', type: 'api-gateway', x: 280, y: 220 },
        { id: 'load-balancer', label: 'Load Balancer', type: 'load-balancer', x: 520, y: 220 },
        { id: 'server-1', label: 'Server 1', type: 'server', x: 750, y: 110 },
        { id: 'server-2', label: 'Server 2', type: 'server', x: 750, y: 220 },
        { id: 'server-3', label: 'Server 3', type: 'server', x: 750, y: 330 },
        { id: 'database', label: 'Database', type: 'database', x: 1150, y: 220 },
      ],
      edges: [
        { id: 'client-gw', from: 'client', to: 'api-gateway' },
        { id: 'gw-lb', from: 'api-gateway', to: 'load-balancer' },
        { id: 'lb-s1', from: 'load-balancer', to: 'server-1' },
        { id: 'lb-s2', from: 'load-balancer', to: 'server-2' },
        { id: 'lb-s3', from: 'load-balancer', to: 'server-3' },
        { id: 's1-db', from: 'server-1', to: 'database' },
        { id: 's2-db', from: 'server-2', to: 'database' },
        { id: 's3-db', from: 'server-3', to: 'database' },
      ],
      viewBox: '0 0 1300 440',
      engineId: 'stage-6',
      enterLabel: '',  // Final fix, no next step
      description: 'API Gateway filters bad traffic. 20% rejected, 9.6K clean requests pass to servers.',
      whatCondition: '12K attempted RPS. API Gateway validates, rate limits, rejects 20% (bots, malformed). Only 9.6K clean requests reach servers. Each server at 32% CPU.',
      howToResolve: 'Gateway protects servers from overload. Bad actors are rejected at the edge. Servers focus on legitimate traffic.',
    },
  ],
  nodes: [
    { id: 'client', label: 'Client', type: 'client', x: 100, y: 220 },
    { id: 'server-1', label: 'Server 1', type: 'server', x: 400, y: 110 },
    { id: 'server-2', label: 'Server 2', type: 'server', x: 400, y: 220 },
    { id: 'server-3', label: 'Server 3', type: 'server', x: 400, y: 330 },
    { id: 'database', label: 'Database', type: 'database', x: 750, y: 220 },
  ],
  edges: [
    { id: 'client-s1', from: 'client', to: 'server-1' },
    { id: 'client-s2', from: 'client', to: 'server-2' },
    { id: 'client-s3', from: 'client', to: 'server-3' },
    { id: 's1-db', from: 'server-1', to: 'database' },
    { id: 's2-db', from: 'server-2', to: 'database' },
    { id: 's3-db', from: 'server-3', to: 'database' },
  ],
  viewBox: '0 0 900 440',
}

// Stage 4: Load Balancer & Health Checks (NEW, with multiple fixes)
export const stage4: Stage = {
  id: 'stage-loadbalancer',
  title: 'Load Balancer',
  subtitle: 'Distribute Load & Detect Failures',
  insight: 'Single server crashes with traffic spike. Horizontal scaling + LB solves it.',
  displayTitle: 'Horizontal Scaling & Load Balancing',
  description: 'Scale horizontally and use load balancing to handle spikes and failures.',
  components: ['Client', 'Load Balancer', 'Server ×3', 'Database'],
  infoCard: {
    technicalTerm: 'Horizontal Scaling & Load Balancing',
    whenHappens: 'When a single server cannot handle traffic spikes. Vertical scaling has hard limits. Horizontal scaling is required but introduces new distribution challenges.',
    whatCondition: '8K RPS spike overwhelms a single server. CPU hits 98%. Latency spikes to 500ms. Error rate 25%. If server dies, all requests fail.',
    howToResolve: 'Add more servers horizontally. But without a load balancer, traffic routes unevenly causing hotspots. Solution: Use a load balancer with health checks.',
  },
  fixModes: [
    {
      nodes: [
        { id: 'client', label: 'Client', type: 'client', x: 100, y: 220 },
        { id: 'server-1', label: 'Server 1', type: 'server', x: 450, y: 110 },
        { id: 'server-2', label: 'Server 2', type: 'server', x: 450, y: 220 },
        { id: 'server-3', label: 'Server 3', type: 'server', x: 450, y: 330 },
        { id: 'database', label: 'Database', type: 'database', x: 850, y: 220 },
      ],
      edges: [
        { id: 'client-s1', from: 'client', to: 'server-1' },
        { id: 'client-s2', from: 'client', to: 'server-2' },
        { id: 'client-s3', from: 'client', to: 'server-3' },
        { id: 's1-db', from: 'server-1', to: 'database' },
        { id: 's2-db', from: 'server-2', to: 'database' },
        { id: 's3-db', from: 'server-3', to: 'database' },
      ],
      viewBox: '0 0 1050 440',
      engineId: 'stage-lb-problem',
      enterLabel: 'Add More Servers',
      description: 'Added 3 servers but no load balancer. Traffic routes unevenly (hotspot). Server-1 at 72% CPU, others mostly idle.',
      whatCondition: '9K RPS across 3 servers but uneven routing. Server-1 becomes a hotspot at 72% CPU (70% of traffic). Server-2 and Server-3 idle at 15% each. Single-point-of-failure if Server-1 crashes.',
      howToResolve: 'Add a Load Balancer to distribute traffic evenly and monitor server health. LB detects dead servers automatically.',
    },
    {
      nodes: [
        { id: 'client', label: 'Client', type: 'client', x: 100, y: 220 },
        { id: 'load-balancer', label: 'Load Balancer', type: 'load-balancer', x: 350, y: 220 },
        { id: 'server-1', label: 'Server 1', type: 'server', x: 620, y: 110 },
        { id: 'server-2', label: 'Server 2', type: 'server', x: 620, y: 220 },
        { id: 'server-3', label: 'Server 3', type: 'server', x: 620, y: 330 },
        { id: 'database', label: 'Database', type: 'database', x: 950, y: 220 },
      ],
      edges: [
        { id: 'client-lb', from: 'client', to: 'load-balancer' },
        { id: 'lb-s1', from: 'load-balancer', to: 'server-1' },
        { id: 'lb-s2', from: 'load-balancer', to: 'server-2' },
        { id: 'lb-s3', from: 'load-balancer', to: 'server-3' },
        { id: 's1-db', from: 'server-1', to: 'database' },
        { id: 's2-db', from: 'server-2', to: 'database' },
        { id: 's3-db', from: 'server-3', to: 'database' },
      ],
      viewBox: '0 0 1100 440',
      engineId: 'stage-5',
      enterLabel: '',  // Final fix, no next step
      description: 'Load Balancer distributes traffic evenly. Health checks detect failures. Each server at 30% CPU.',
      whatCondition: '9K RPS evenly distributed via LB: 3K per server, 30% CPU each. Health checks detect dead servers and remove from rotation. Zero errors even during failures.',
      howToResolve: 'Load Balancer is the solution. It automatically distributes traffic and detects failures. Servers stay healthy and responsive.',
    },
  ],
  nodes: [
    { id: 'client', label: 'Client', type: 'client', x: 150, y: 200 },
    { id: 'server', label: 'Server', type: 'server', x: 450, y: 200 },
    { id: 'database', label: 'Database', type: 'database', x: 750, y: 200 },
  ],
  edges: [
    { id: 'client-server', from: 'client', to: 'server' },
    { id: 'server-db', from: 'server', to: 'database' },
  ],
  viewBox: '0 0 900 400',
}

// Stage 5: DB Bottleneck (old stage-7)
export const stage5: Stage = {
  id: 'stage-7',
  title: 'DB Bottleneck',
  subtitle: 'Database Saturation — Connection Pool Exhausted',
  insight: 'DB connection pool at 95%. Latency climbs to 250ms.',
  displayTitle: 'Database Bottleneck',
  description: 'Connection pool saturates as all servers hammer the same database.',
  components: ['Client', 'API Gateway', 'Load Balancer', 'Server ×3', 'Database'],
  infoCard: {
    technicalTerm: 'Database Connection Pool Exhaustion',
    whenHappens: 'When request rate outpaces database ability to handle concurrent connections. Typically hits at 10K+ RPS.',
    whatCondition: 'The DB connection pool climbs to 95%. New queries wait in queue. Latency jumps from 45ms to 250ms. Errors start appearing. Servers are healthy. The database is the single bottleneck.',
    howToResolve: 'Add a cache layer to absorb repetitive reads. 80% of queries are often for the same hot data. Serving those from cache eliminates 80% of DB load.',
  },
  nodes: [
    { id: 'client', label: 'Client', type: 'client', x: 80, y: 220 },
    { id: 'api-gateway', label: 'API Gateway', type: 'api-gateway', x: 280, y: 220 },
    { id: 'load-balancer', label: 'Load Balancer', type: 'load-balancer', x: 520, y: 220 },
    { id: 'server-1', label: 'Server 1', type: 'server', x: 750, y: 110 },
    { id: 'server-2', label: 'Server 2', type: 'server', x: 750, y: 220 },
    { id: 'server-3', label: 'Server 3', type: 'server', x: 750, y: 330 },
    { id: 'database', label: 'Database', type: 'database', x: 1150, y: 220 },
  ],
  edges: [
    { id: 'client-gw', from: 'client', to: 'api-gateway' },
    { id: 'gw-lb', from: 'api-gateway', to: 'load-balancer' },
    { id: 'lb-s1', from: 'load-balancer', to: 'server-1' },
    { id: 'lb-s2', from: 'load-balancer', to: 'server-2' },
    { id: 'lb-s3', from: 'load-balancer', to: 'server-3' },
    { id: 's1-db', from: 'server-1', to: 'database' },
    { id: 's2-db', from: 'server-2', to: 'database' },
    { id: 's3-db', from: 'server-3', to: 'database' },
  ],
  viewBox: '0 0 1300 440',
}

// Stage 6: Cache Layer (old stage-8)
export const stage6: Stage = {
  id: 'stage-8',
  title: 'Cache Layer',
  subtitle: 'Caching — Hit Rate 80%, Latency Drops',
  insight: '80% cache hits. Latency drops to 35ms. DB load halved.',
  displayTitle: 'Read-Through Cache',
  description: '80% of reads served from cache. DB queries drop by 80%. Latency falls to 35ms.',
  components: ['Client', 'API Gateway', 'Load Balancer', 'Server ×3', 'Cache ×3', 'Database'],
  infoCard: {
    technicalTerm: 'Read-Through Cache (Redis/Memcached)',
    whenHappens: 'After identifying database as bottleneck. Cache sits between application servers and database.',
    whatCondition: '80% of reads are cache hits served in <5ms. Only 20% of reads miss cache and query DB. DB connection pool drops to 25%. Latency falls from 250ms to 35ms.',
    howToResolve: 'Cache is highly effective for read-heavy workloads. At scale, a well-tuned cache absorbs 90%+ of read traffic.',
  },
  nodes: [
    { id: 'client', label: 'Client', type: 'client', x: 120, y: 220 },
    { id: 'api-gateway', label: 'API Gateway', type: 'api-gateway', x: 320, y: 220 },
    { id: 'load-balancer', label: 'Load Balancer', type: 'load-balancer', x: 540, y: 220 },
    { id: 'server-1', label: 'Server 1', type: 'server', x: 750, y: 110 },
    { id: 'server-2', label: 'Server 2', type: 'server', x: 750, y: 220 },
    { id: 'server-3', label: 'Server 3', type: 'server', x: 750, y: 330 },
    { id: 'cache-1', label: 'Cache 1', type: 'cache', x: 1020, y: 140 },
    { id: 'cache-2', label: 'Cache 2', type: 'cache', x: 1020, y: 220 },
    { id: 'cache-3', label: 'Cache 3', type: 'cache', x: 1020, y: 300 },
    { id: 'database', label: 'Database', type: 'database', x: 1350, y: 220 },
  ],
  edges: [
    { id: 'client-gw', from: 'client', to: 'api-gateway' },
    { id: 'gw-lb', from: 'api-gateway', to: 'load-balancer' },
    { id: 'lb-s1', from: 'load-balancer', to: 'server-1' },
    { id: 'lb-s2', from: 'load-balancer', to: 'server-2' },
    { id: 'lb-s3', from: 'load-balancer', to: 'server-3' },
    { id: 's1-cache1', from: 'server-1', to: 'cache-1' },
    { id: 's1-cache2', from: 'server-1', to: 'cache-2' },
    { id: 's2-cache1', from: 'server-2', to: 'cache-1' },
    { id: 's2-cache2', from: 'server-2', to: 'cache-2' },
    { id: 's2-cache3', from: 'server-2', to: 'cache-3' },
    { id: 's3-cache2', from: 'server-3', to: 'cache-2' },
    { id: 's3-cache3', from: 'server-3', to: 'cache-3' },
    { id: 'cache1-db', from: 'cache-1', to: 'database' },
    { id: 'cache2-db', from: 'cache-2', to: 'database' },
    { id: 'cache3-db', from: 'cache-3', to: 'database' },
  ],
  viewBox: '0 0 1600 440',
}

// Stage 7: Cache Failure (old stage-9)
export const stage7: Stage = {
  id: 'stage-9',
  title: 'Cache Failure',
  subtitle: 'Cache Node Down — Hit Rate Degrades',
  insight: 'Cache fails. Hit rate drops 80%→40%. Latency climbs.',
  displayTitle: 'Cache Node Failure',
  description: 'One cache node dies. Hit rate degrades 80% → 40%. Latency climbs back up.',
  components: ['Client', 'API Gateway', 'Load Balancer', 'Server ×3', 'Cache ×3', 'Database'],
  infoCard: {
    technicalTerm: 'Cache Node Failure / Cache Stampede Risk',
    whenHappens: 'Cache nodes are in-memory systems. Without redundancy, a single failure causes a flood of DB queries.',
    whatCondition: 'Cache-2 node dies. Hit rate drops 80% to 40%. DB receives double the queries. Latency climbs from 35ms back to 180ms. Connection pool usage spikes to 85%.',
    howToResolve: 'Cache clusters with replication. Keys distributed across multiple nodes. One node failure affects only ~33% of keys.',
  },
  nodes: [
    { id: 'client', label: 'Client', type: 'client', x: 120, y: 220 },
    { id: 'api-gateway', label: 'API Gateway', type: 'api-gateway', x: 320, y: 220 },
    { id: 'load-balancer', label: 'Load Balancer', type: 'load-balancer', x: 540, y: 220 },
    { id: 'server-1', label: 'Server 1', type: 'server', x: 750, y: 110 },
    { id: 'server-2', label: 'Server 2', type: 'server', x: 750, y: 220 },
    { id: 'server-3', label: 'Server 3', type: 'server', x: 750, y: 330 },
    { id: 'cache-1', label: 'Cache 1', type: 'cache', x: 1020, y: 140 },
    { id: 'cache-2', label: 'Cache 2', type: 'cache', x: 1020, y: 220 },
    { id: 'cache-3', label: 'Cache 3', type: 'cache', x: 1020, y: 300 },
    { id: 'database', label: 'Database', type: 'database', x: 1350, y: 220 },
  ],
  edges: [
    { id: 'client-gw', from: 'client', to: 'api-gateway' },
    { id: 'gw-lb', from: 'api-gateway', to: 'load-balancer' },
    { id: 'lb-s1', from: 'load-balancer', to: 'server-1' },
    { id: 'lb-s2', from: 'load-balancer', to: 'server-2' },
    { id: 'lb-s3', from: 'load-balancer', to: 'server-3' },
    { id: 's1-cache1', from: 'server-1', to: 'cache-1' },
    { id: 's1-cache2', from: 'server-1', to: 'cache-2' },
    { id: 's2-cache1', from: 'server-2', to: 'cache-1' },
    { id: 's2-cache2', from: 'server-2', to: 'cache-2' },
    { id: 's2-cache3', from: 'server-2', to: 'cache-3' },
    { id: 's3-cache2', from: 'server-3', to: 'cache-2' },
    { id: 's3-cache3', from: 'server-3', to: 'cache-3' },
    { id: 'cache1-db', from: 'cache-1', to: 'database' },
    { id: 'cache2-db', from: 'cache-2', to: 'database' },
    { id: 'cache3-db', from: 'cache-3', to: 'database' },
  ],
  viewBox: '0 0 1600 440',
}

// Stage 8: Full Resilience (old stage-10)
export const stage8: Stage = {
  id: 'stage-10',
  title: 'Full Resilience',
  subtitle: 'Multi-Tier System — 15K RPS, Zero Errors',
  insight: '15K RPS. All healthy. 85% cache hit. 28ms latency.',
  displayTitle: 'Full Resilience Architecture',
  description: 'Multi-tier system at 15K RPS. All nodes healthy. Zero errors.',
  components: ['Client', 'API Gateway', 'Load Balancer', 'Server ×3', 'Cache ×3', 'Database'],
  infoCard: {
    technicalTerm: 'Multi-Tier Resilient Architecture',
    whenHappens: 'The end state of systematic scaling. Each tier is redundant, monitored, independently scalable.',
    whatCondition: '15K RPS. API gateway handles auth and rate limiting. LB distributes across 3 healthy servers. Redis cluster absorbs 85% of reads. DB handles 15% of queries. Zero errors.',
    howToResolve: 'This architecture scales to 1M+ users by: auto-scaling servers, Redis Cluster for cache, read replicas for DB, CDN at edge.',
  },
  nodes: [
    { id: 'client', label: 'Client', type: 'client', x: 120, y: 220 },
    { id: 'api-gateway', label: 'API Gateway', type: 'api-gateway', x: 320, y: 220 },
    { id: 'load-balancer', label: 'Load Balancer', type: 'load-balancer', x: 540, y: 220 },
    { id: 'server-1', label: 'Server 1', type: 'server', x: 750, y: 110 },
    { id: 'server-2', label: 'Server 2', type: 'server', x: 750, y: 220 },
    { id: 'server-3', label: 'Server 3', type: 'server', x: 750, y: 330 },
    { id: 'cache-1', label: 'Cache 1', type: 'cache', x: 1020, y: 140 },
    { id: 'cache-2', label: 'Cache 2', type: 'cache', x: 1020, y: 220 },
    { id: 'cache-3', label: 'Cache 3', type: 'cache', x: 1020, y: 300 },
    { id: 'database', label: 'Database', type: 'database', x: 1350, y: 220 },
  ],
  edges: [
    { id: 'client-gw', from: 'client', to: 'api-gateway' },
    { id: 'gw-lb', from: 'api-gateway', to: 'load-balancer' },
    { id: 'lb-s1', from: 'load-balancer', to: 'server-1' },
    { id: 'lb-s2', from: 'load-balancer', to: 'server-2' },
    { id: 'lb-s3', from: 'load-balancer', to: 'server-3' },
    { id: 's1-cache1', from: 'server-1', to: 'cache-1' },
    { id: 's1-cache2', from: 'server-1', to: 'cache-2' },
    { id: 's2-cache1', from: 'server-2', to: 'cache-1' },
    { id: 's2-cache2', from: 'server-2', to: 'cache-2' },
    { id: 's2-cache3', from: 'server-2', to: 'cache-3' },
    { id: 's3-cache2', from: 'server-3', to: 'cache-2' },
    { id: 's3-cache3', from: 'server-3', to: 'cache-3' },
    { id: 'cache1-db', from: 'cache-1', to: 'database' },
    { id: 'cache2-db', from: 'cache-2', to: 'database' },
    { id: 'cache3-db', from: 'cache-3', to: 'database' },
  ],
  viewBox: '0 0 1600 440',
}

export const stages: Stage[] = [
  stage1,
  stage2,
  stage3,
  stage4,
  stage5,
  stage6,
  stage7,
  stage8,
]
